# Главные настройки
<system>
  log_level info
  suppress_repeated_stacktrace true
  emit_error_log_interval 30s
  #suppress_config_dump true  # Не выводить конфигурацию в логи
</system>

# Источник данных
<source>
  @type forward
  port 24224
  #bind 0.0.0.0  # Привязка к внутренней сети

  # Ограничение размера принимаемых данных
  #chunk_size_limit 2M
  #chunk_size_warn_limit 1M
</source>

<source>
  @type http
  port 9880
</source>

# Базовый фильтр для валидации данных
<filter **>
  @type record_transformer
  enable_ruby false  # Отключение выполнение Ruby кода извне

  <record>
    # Добавление метаданные для отслеживания
    fluentd_received_at ${time}
    fluentd_hostname "#{Socket.gethostname}"
  </record>
</filter>

# Защита от сообщений больше 100KB
#<filter **>
#  @type grep
#  <exclude>
#    key message
#    pattern /.{100000,}/
#  </exclude>
#</filter>

<match api.logs>
  @type elasticsearch
  host elasticsearch  # Использование DNS имя сервиса из Docker
  port 9200
  index_name api-logs-%Y%m%d
  #user elastic
  #password "#{ENV['ELASTIC_PASSWORD']}"  # Пароль из переменных окружения

  scheme http  # Используем HTTP, так как трафик внутри защищенной сети Docker
  ssl_verify false  # Отключаем проверку SSL для внутренней сети

  # Настройки индексов

  # Защита от перегрузки
  request_timeout 30s
  reload_connections false
  reconnect_on_error true
  reload_on_failure true
  flush_interval 5s

  # Буферизация для устойчивости
  <buffer tag>
    @type file
    path /fluentd/log/buffer
    flush_mode interval
    flush_interval 5s
    retry_type exponential_backoff
    retry_wait 1s
    retry_max_interval 60s
    retry_timeout 24h
    chunk_limit_size 16MB
    total_limit_size 2GB
    overflow_action block
  </buffer>
</match>

# Обработка ошибок (запись в файл)
#<label @ERROR>
#  <match **>
#    @type file
#    path /fluentd/log/error
#    compress gzip
#    <buffer>
#      timekey 1d
#      timekey_use_utc true
#      timekey_wait 10m
#    </buffer>
#  </match>
#</label>